import { useParams } from "react-router-dom";
import "../PetPost.css";

const PetData ={
    1: {
        title:'Dog SShih Tzu',
        summary: 'Shih Tzus are small, long-haired dogs known for their affectionate and playful personalities, making them great family pets. They are relatively low-energy, enjoy gentle walks, and adapt well to apartment living. Their long, silky coat requires regular grooming, but they are generally healthy and have a lifespan of 10-16 years.Shih Tzus are largely associated with Buddhism and Buddhist mythology. The name "Shih Tzu" in Mandarin directly translates to "little lion," an animal considered sacred in Buddhist religion. Lions symbolize royalty, strength, and bravery "fear nothing, and act without delay." Pairs of stone lions or lion dogs located outside guard palace doors, tombs, temples, and public buildings are thought to protect these buildings from harmful individuals and spiritual influences. These stone statues are often called Fu (or Foo) dogs, and it is suggested that these are the lionized form of the Shih Tzu.[15] "Fu" roughly translates to "happiness" in Manchurian, with legend stating Fu dogs are happy Shih Tzus forever guarding the temple of Buddha. Fu dog statues typically represent a male and female Shih Tzu, carved out of stone, jade, teak, ivory, cinnabar, bronze, or ceramics. The male dog is often seen holding a ball with his left paw and the female dog holds her puppy. Sources state this holds a symbolic meaning, with the male dog representing powers over nature, energy, wisdom, and precious stones and the female dog symbolizing protection, play, and a disciplinary attitude.In contemporary Mandarin, the Shih Tzu is generally known as the "Xi Shi dog"; Xi Shi was regarded as one of the most beautiful women of ancient China. Shih Tzu was nicknamed the "chrysanthemum dog" in England in the 1930s. The dog may also be called the Tibetan Lion Dog, but whether the breed should be referred to as "Tibetan" or "Chinese" is a source of both historical and political contention, and dog historians tend to have very strong opinions on the subject.'  
    },

    2: {
        title: 'Golden Retriever',
        summary: 'Golden Retrievers are large, friendly, and intelligent dogs known for their lustrous golden coats. They are popular family pets due to their gentle, playful, and eager-to-please nature. Originally bred as working dogs, they are energetic and require regular exercise and mental stimulation.The Golden Retriever was developed in Scotland in the nineteenth century by Sir Dudley Marjoribanks (later to become Baron Tweedmouth) from Flat-coated Retrievers judiciously crossed with Tweed Water Spaniels and some other British dog breeds. Prior to the 1952 publication of the very detailed stud book which had been meticulously maintained by Marjoribanks, a number of romantic tales were published about the origins of the breed.In the 1860s Marjoribanks set out to create what to his mind was the ultimate breed of retriever at his Scottish estate Guisachan. He started by acquiring a yellow-coloured Flat-coated Retriever dog called Nous;[note 1] Nous had been whelped in June 1864 and was the only yellow pup in an otherwise all black-coloured litter. Whilst uncommon, occasionally liver, brown, golden or yellow-coloured purebred Flat-coated Retriever pups are whelped to matings of two black parents. It is the pedigree of Nous that was the source for the romantic tales of the heritage of the Golden Retriever. One early account claimed Nous was purchased from a Russian circus trainer in Brighton, another claimed he was bought from a cobbler, and yet another claimed a gypsy. The stud book states that Nous was a Flat-coated Retriever bred by Lord Chichester on his Stanmer Park estate near Brighton.The Golden Retriever was bred by Sir Dudley Marjoribanks at his Scottish estate Guisachan in the late nineteenth century. He cross-bred Flat-coated Retrievers with Tweed Water Spaniels, with some further infusions of Red Setter, Labrador Retriever and Bloodhound. It was recognised by the Kennel Club in 1913, and during the interwar period spread to many parts of the world.'
    },

    3: {
        title: 'Rottweiler',
        summary: 'The Rottweiler is a breed of domestic dog, regarded as medium-to-large or large. The dogs were known in German as Rottweiler Metzgerhund, meaning Rottweil butchers dogs, because their main use was to herd livestock and pull carts laden with butchered meat to market.According to the FCI Standard, the Rottweiler is considered to be one of the oldest surviving dog breeds. Its origin goes back to Roman times. These dogs were kept as herder or driving dogs. They marched over the Alps with the Roman legions, protecting the humans and driving their cattle. In the region of Rottweil, these dogs met and mixed with the native dogs in a natural crossing. The main task of the Rottweiler now became the driving and guarding of the herds of cattle and the defence of their masters and their property. This breed acquired its name from the old free city of Rottweil and was known as the "Rottweil butchers dog". The butchers bred this type of dog purely for performance and usefulness. In due course, a first rate watch and driving dog evolved which could also be used as a draught dog.The Deutscher Rottweiler-Klub (DRK, German Rottweiler Club), the first Rottweiler club in Germany, was founded on 13 January 1914, and followed by the creation of the Süddeutscher Rottweiler-Klub (SDRK, South German Rottweiler Club) on 27 April 1915 and eventually became the IRK (International Rottweiler Club). The DRK counted around 500 Rottweilers, and the SDRK 3,000 Rottweilers. The goals of the two clubs were different. The DRK aimed to produce working dogs and did not emphasise the morphology of the Rottweiler.The various German Rottweiler Clubs amalgamated to form the Allgemeiner Deutscher Rottweiler Klub (ADRK, General German Rottweiler Club) in 1921. This was officially recorded in the register of clubs and associations at the district court of Stuttgart on 27 January 1924. The ADRK is recognised worldwide as the home club of the Rottweiler.'
    },

    4: {
        title: 'Persian cat',
        summary: 'Persian cats are a long-haired breed known for their sweet, gentle, and affectionate personalities, as well as their distinctive flat faces and long, luxurious coats. They are generally calm, quiet, and enjoy lounging around, making them well-suited for indoor living.The Persian cat, also known as the Persian Longhair or simply Persian, is a long-haired breed of cat characterised by a round face and short muzzle. The first documented ancestors of Persian cats might have been imported into Italy from Khorasan as early as around 1620, but this has not been proven. Instead, there is stronger evidence for a longhaired cat breed being exported from Afghanistan and Iran/Persia from the 19th century onwards. Persian cats have been widely recognised by the North-West European cat fancy since the 19th century, and after World War II by breeders from North America, Australia and New Zealand. Some cat fancier organisations breed standards subsume the Himalayan and Exotic Shorthair as variants of this breed, while others generally treat them as separate breeds.The selective breeding carried out by breeders has allowed the development of a wide variety of coat colours,[5] but has also led to the creation of increasingly flat-faced Persian cats. Favoured by fanciers, this head structure can bring with it several health problems. As is the case with the Siamese breed, there have been efforts by some breeders to preserve the older type of cat, the Traditional Persian, which has a more pronounced muzzle. Hereditary polycystic kidney disease (PKD) is prevalent in the breed, affecting almost half of the population in some countries.The first documented ancestors of the Persian cat might have been imported from Khorasan, either Eastern Iran or Western Afghanistan, into the Italian Peninsula in 1620 by Pietro Della Valle; and from Damascus, Syria, into France by Nicolas-Claude Fabri de Peiresc at around the same time. While the de Peiresc import from Syria is corroborated by later correspondences, Della Valle is only known to have voiced his intention in a letter from 1620 but returned to Italy much later in 1626 after travelling several other countries with the remains of his wife in tow and no further mention of the cats.'
    },

    5: {
        title: 'Himalayan cat',
        summary: 'The Himalayan, is a breed or sub-breed of long-haired cat similar in type to the Persian, with the exception of its blue eyes and its point colouration, which were derived from crossing the Persian with the Siamese.Work to formally establish a breed with combined Persian and Siamese traits, explicitly for the cat fancy, began in the United States in the 1930s at Harvard University, under the term Siamese Persian, and the results were published in the Journal of Heredity in 1936, but were not adopted as a recognised breed by any major fancier groups at the time. Brian Sterling-Webb independently developed the cross-breed over a period of ten years in the UK, and in 1955 it was recognised there as the Longhaired Colourpoint by the Governing Council of the Cat Fancy (GCCF).Cat breeder Jean Mill from California, US, took a series of graduate classes in genetics at the University of California, Davis. By 1948, she was one of three breeders independently crossing the Persian and Siamese to create the Himalayan cat.Separate US-based breeding efforts had begun around 1950, and a breeder known to sources simply as Mrs. Goforth received breed recognition from the Cat Fanciers Association (CFA) near the end of 1957 for the Himalayan. Early breeders were mostly interested in adding Siamese colouration to long-haired cats, and therefore reinforced the stock by outbreeding to Persians only to retain the Persian trait dominance. However, by the 1960s, some were re-introducing Siamese stock and producing less "Persian-style" cats, In the 1980s, a concerted effort to re-establish the breed along more formally Persian lines ultimately caused the breed to be merged into Persian as a variant in some registries (e.g. in 1984 by CFA), and a decline in the "old" or Siamese-like specimens.'
    },

    6: {
        title: 'British Shorthair',
        summary: 'The British Shorthair is the pedigree version of the traditional British domestic cat, with a distinctively stocky body, thick coat, and broad face. The most familiar colour variant is the "British Blue", with a solid grey-blue coat, pineapple eyes, and a medium-sized tail.Selective breeding of the best examples of the type began in the nineteenth century, with emphasis on developing the unusual blue-grey variant called the "British Blue" or "English type" (to distinguish it from the more fine-boned "Russian type"). Some sources directly credit UK artist and pioneering cat fancier Harrison Weir with the initial concept of standardising the breed. Others suggest a group of breeders may have been involved. The new British Shorthair was featured at the first-ever cat show, organised by Weir and held at the Crystal Palace in London in 1871, and enjoyed great initial popularity.By the 1900s with the advent of the newly imported Persian and other long-haired breeds, the British Shorthair had fallen out of favour, and breeding stock had become critically rare by World War I.[6][page needed] At least partially to alleviate this, British Shorthair breeders mixed Persians into their bloodlines.[citation needed] The genes thus introduced would eventually become the basis for the British Longhair. At the time, any long-haired cats produced were placed into the Persian breeding program.[citation needed] As all cats with the blue colouration were then judged together as variants on a de facto single breed, the Blue Shorthair, outcrossings of the British with the Russian Blue were also common.After the war, in an attempt to maintain the breed standard, the GCCF decided to accept only third-generation Persian/British Shorthair crosses.[citation needed] This contributed to another shortage of pure breeding stock by World War II, at which point the Persian and Russian Blue were reintroduced into the mix.'
    },

    7: {
        title: 'Parrot',
        summary: 'Parrots, also known as psittacines, are birds with a strong curved beak, upright stance, and clawed feet. They are classified in four families that contain roughly 410 species in 101 genera, found mostly in tropical and subtropical regions.Psittaciform diversity in South America and Australasia suggests that the order may have evolved in Gondwana, centred in Australasia.[8] The scarcity of parrots in the fossil record, however, presents difficulties in confirming the hypothesis. There is currently a higher number of fossil remains from the northern hemisphere in the early Cenozoic.[9] Molecular studies suggest that parrots evolved approximately 59 million years ago (Mya) (range 66–51 Mya) in Gondwana. The Neotropical parrots are monophyletic, and the three major clades originated about 50 Mya (range 57–41 Mya).A single 15 mm (0.6 in) fragment from a large lower bill (UCMP 143274), found in deposits from the Lance Creek Formation in Niobrara County, Wyoming, had been thought to be the oldest parrot fossil and is presumed to have originated from the Late Cretaceous period, which makes it about 70 million years old.[11] However, other studies suggest that this fossil is not from a bird, but from a caenagnathid oviraptorosaur (a non-avian dinosaur with a birdlike beak), as several details of the fossil used to support its identity as a parrot are not actually exclusive to parrots, and it is dissimilar to the earliest-known unequivocal parrot fossils.It is generally assumed that the Psittaciformes were present during the Cretaceous–Paleogene extinction event (K-Pg extinction), 66 mya. They were probably generalised arboreal birds, and did not have the specialised crushing bills of modern species.[9][14] Genomic analysis provides strong evidence that parrots are the sister group of passerines, forming the clade Psittacopasserae, which is the sister group of the falcons.'
    },

    8: {
        title: 'Lovebirds',
        summary: 'Lovebird is the common name for the genus Agapornis, a small group of parrots in the Old World parrot family Psittaculidae. Of the nine species in the genus, all are native to the African continent, with the grey-headed lovebird being native to the African island of Madagascar.Social and affectionate, the name comes from the parrots strong, monogamous pair bonding and the long periods which paired birds spend sitting together. Lovebirds live in small flocks and eat fruit, vegetables, grasses, and seeds. Some species are kept as pets, and several coloured mutations have been selectively bred in aviculture. The average lifespan is 10 to 12 years.. Wildtype lovebirds are mostly green with a variety of colours on their upper body, depending on the species. The Fischers lovebird, black-cheeked lovebird, and the masked lovebird have a prominent white ring around their eyes. Many colour mutant varieties have been produced by selective breeding of the species that are popular in aviculture.[citation needed] As of 2019, there are 30 known plumage colour variations among lovebirds, which are caused by pigments called psittacofulvins.The genus Agapornis was described by the English naturalist Prideaux John Selby in 1836. The name combines the Ancient Greek αγάπη agape meaning "love" and όρνις ornis meaning "bird". The type species is the black-collared lovebird (Agapornis swindernianus), which was originally placed into the genus Psittacus within a section called Psittacula by naturalist Heinrich Kuhl. Selby contended that this placement rather than a separate genus was "artificial" and done "without regard to the structure, habits, or distribution of the species.'
    },

    9: {
        title: 'Rabbit',
        summary: 'Rabbits or bunnies are small mammals in the family Leporidae, which is in the order Lagomorpha. They are familiar throughout the world as a small herbivore, a prey animal, a domesticated form of livestock, and a pet, having a widespread effect on ecologies and cultures.Rabbits are a paraphyletic grouping, and do not constitute a clade, as hares (belonging to the genus Lepus) are nested within the Leporidae clade and are not described as rabbits. Although once considered rodents, lagomorphs diverged earlier and have a number of traits rodents lack, including two extra incisors. Similarities between rabbits and rodents were once attributed to convergent evolution, but studies in molecular biology have found a common ancestor between lagomorphs and rodents and place them in the clade Glires.Rabbit physiology is suited to escaping predators and surviving in various habitats, living either alone or in groups in nests or burrows. As prey animals, rabbits are constantly aware of their surroundings, having a wide field of vision and ears with high surface area to detect potential predators. The ears of a rabbit are essential for thermoregulation and contain a high density of blood vessels. The bone structure of a rabbits hind legs, which is longer than that of the fore legs, allows for quick hopping, which is beneficial for escaping predators and can provide powerful kicks if captured. Rabbits are typically nocturnal and often sleep with their eyes open. They reproduce quickly, having short pregnancies, large litters of four to twelve kits, and no particular mating season; however, the mortality rate of rabbit embryos is high, and there exist several widespread diseases that affect rabbits, such as rabbit hemorrhagic disease and myxomatosis. In some regions, especially Australia, rabbits have caused ecological problems and are regarded as a pest.'
       
    },
};

function PetPost() {
    const { id } = useParams();
    const post = PetData[id];

    return (
        <div className="pet-post-container">
            <h2>{post.title}</h2>
            <p>{post.summary}</p>
        </div>
    );
}

export default PetPost;

